all:
	mex -O fst_accumulate.c
	mex -O fst_addvec.c
	mex -O fst_dgemm.c
	mex -O fst_diagmul.c
	mex -O fst_dspamm.c
	mex -O fst_dspammt2.c
	mex -O fst_dspammt.c
	mex -O fst_dsymm.c
	mex -O fst_dsyrk.c
	mex -O fst_dtrmm.c
	mex -O fst_dtrsm.c
	mex -O fst_flipdims.c
	mex -O fst_getsparse.c
	mex -O fst_invchol.c
	mex -O fst_muldiag.c
	mex -O fst_permute.c
	mex -O fst_reshape.c
	mex -O fst_sumpos.c
	mex -O save_sparse.c

clean:
	rm -f *.o *.mexglx *~ \#*
